# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ElysiaAI\ElysiaUI.ui'
#
# Created by: PySide2 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 400))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        
        self.dialog = QtWidgets.QWidget()
        self.dialog.setGeometry(QtCore.QRect(0, 0, 500, 403))
        self.dialog.setMinimumSize(QtCore.QSize(700, 400))
        self.dialog.setMaximumSize(QtCore.QSize(700, 16777215))
        self.dialog.setObjectName("dialog")
        self.label_hello = QtWidgets.QLabel(self.dialog)
        self.label_hello.setGeometry(QtCore.QRect(10, 20, 441, 22))
        self.label_hello.setMinimumSize(QtCore.QSize(114514, 30))
        self.label_hello.setMaximumSize(QtCore.QSize(114514, 114514))
        self.label_hello.setObjectName("label_hello")
        
        self.scrollArea.setWidget(self.dialog)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pbtn_send = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_send.setMinimumSize(QtCore.QSize(80, 30))
        self.pbtn_send.setMaximumSize(QtCore.QSize(80, 30))
        self.pbtn_send.setObjectName("pbtn_send")
        self.horizontalLayout.addWidget(self.pbtn_send)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle("嗨~想我了吗?无论何时何地,爱莉希雅都会回应你的期待♪")
        self.pbtn_send.setText(_translate("MainWindow", "发送"))
